apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devx-crgarcia12-modern-winamp-liliput-920ccf05

resources:
- namespace.yaml
- deployment.yaml

images:
- name: crgarliliputacr.azurecr.io/liliput-app-crgarcia12-modern-winamp
  newTag: 5cffaceba308

commonLabels:
  app: modern-winamp
  owner: crgarcia12
  liliput-task: "920ccf05"